version: '3' 

services:

    db:
      image: postgres:13.2
      ports: 
        - 5432:5432
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${USER}
        POSTGRES_PASSWORD: ${PASS}
        POSTGRES_DB: ${DB}
      container_name: postgres

    backend:  
      image: ecommerce-backend
      ports: 
        - 3001:3001
      command: ["/bin/sh", "entrypoint.sh"]
      container_name: backend
      depends_on: 
        - db

    frontend:  
      build: ./frontend
      ports: 
        - 3000:3000
      command: ["npm", "start"]
      environment: 
        - CHOKIDAR_USEPOLLING=true
      volumes:
        - ${pwd}/frontend:/usr/src/app # Let us modify the contents of the container locally
        - ${pwd}/frontend/node_modules:/usr/src/app/node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
      container_name: frontend

volumes: # This is required for the node_modules named volume
    node_modules:
