POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "risto",
    "email": "risto@mail.com",
    "password": "12345",
    "lastname": "kattila",
    "address": "kivikatu",
    "phonenumber": 123456,
    "isAdmin": true
}

###

POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "name": "teemu",
    "password": "kissa"
}

###

DELETE http://localhost:3001/api/products/56
Content-Type: application/json

###

POST http://localhost:3001/api/orders/9
Content-Type: application/json

{
    "id": 1
}

###

PUT http://localhost:3001/api/products/44
Content-Type: application/json

{
    "price": 5
}

###

DELETE http://localhost:3001/api/orders
Content-Type: application/json

{
    "all": [513, 514, 515, 516]
}

###