name: Deployment pipeline

on:
  push:
    branches:
      - Maca-Branch
    # pull_request:    
    #   branches: [main]    
    #   types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
        working-directory: frontend
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000